DROP TABLE HOUSES;
CREATE TABLE HOUSES (HID INTEGER PRIMARY KEY, NAME varchar(30), PASSWORD varchar(30));

DROP TABLE USERS;
CREATE TABLE USERS (ID INTEGER PRIMARY KEY, HID INTEGER, EMAIL varchar(45), NAME varchar(30), PASSWORD varchar(30), WORKLOAD INTEGER);

DROP TABLE CHORES;
CREATE TABLE CHORES (CID INTEGER PRIMARY KEY, ID INTEGER, HID INTEGER, TITLE varchar(30), DESC varchar(200), DIFFICULTY INTEGER, FREQUENCY varchar(30), CREATED_AT varchar(30), STATUS INTEGER, NAME varchar(30));
